name: em-template
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - plotly
  - nglview
  - ipywidgets
  - ipympl
  - jupyterlab>=4.0.0
  - jupyterlab-myst>=2.0.0
