name: em-template
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - plotly
  - nglview
  - imageio
  - ipywidgets
  - ipympl
  - jupyterlab
  - jupyterlab-myst
