name: em-template
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - matplotlib
  - k3d # 3d volume rendering
  - h5py
  - imageio
  - av # instead of imageio-ffmpeg
  - ipywidgets
  - ipympl
  - jupyterlab
  - jupyterlab-myst
  - 'nodejs>=20,<21'
  - mystmd
