name: em-template
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - scipy
  - h5py
  - matplotlib
  - k3d
  - imageio
  - av
  - ipywidgets
  - ipympl
  - jupyterlab
  - jupyterlab-myst
  - 'nodejs>=20,<21'
  - mystmd
